### ISSUE TITLE
Loses some escapes in pre blocks?

### ISSUE THREAD

**Issue by domenic** [tabatkins/highlighter#10]
See https://github.com/whatwg/html/pull/4661.

When I pass the input

```html
<pre>
&lt;iframe sandbox srcdoc="&lt;p>Yeah, you can see it &lt;a href=&amp;quot;/gallery?mode=cover&amp;amp;amp;page=1&amp;quot;>in my gallery&lt;/a>.">&lt;/iframe>
</pre>
```

through Wattsi alone, I get the expected output, i.e. that same HTML, which renders as shown in http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=6959.

When I pass it through Wattsi + highlighter, I get

```html
<c- p="">&lt;</c-><c- f="">iframe</c-> <c- e="">sandbox</c-> <c- e="">srcdoc</c-><c- o="">=</c-><c- s="">"&lt;p&gt;Yeah, you can see it &lt;a href="</c->/<c- e="">gallery</c->?<c- e="">mode</c-><c- o="">=</c-><c- s="">cover&amp;amp;amp;page=1"</c-><c- p="">&gt;</c->in my gallery<c- p="">&lt;/</c-><c- f="">a</c-><c- p="">&gt;</c->."&gt;<c- p="">&lt;/</c-><c- f="">iframe</c-><c- p="">&gt;</c->
```

which notably has `a href="` instead of `a href=&amp;quot;`.

/cc @sideshowbarker in case this is a problem with Wattsi.

**Comment by sideshowbarker** [comment]
I can say for what it’s worth that it’s at least not immediately obvious to me where this problem might be getting introduced. I feel like it should be a relatively easy fix, regardless. But then I’ve not yet actually investigated it at all..

**Comment by tabatkins** [comment]
It's on my side, I can reproduce the issue locally. I'll see what's up.

**Comment by tabatkins** [comment]
Fixed; I was unescaping in the same order I was escaping. You have to *escape* `&` first, so that a `<` isn't first escaped to `&lt;` and then again to `&amp;lt;`. But then you have to *unescape* `&` last, for the same reason, so a `&amp;lt;` isn't unescaped to `&lt;` and then again to `<`.

Anyway, inverted now, just update your server with the latest version.

**Comment by sideshowbarker** [comment]
Thanks much — I’ve pulled the update into the HTML spec build
