### ISSUE TITLE
Server doesn’t return 400 for invalid Web IDL 

### ISSUE THREAD

**Issue by sideshowbarker** [tabatkins/highlighter#14]
As far as I can tell, server.py doesn’t actually return a 400 for invalid Web IDL.

When I test with invalid Web IDL, I see `IDL SYNTAX ERROR` messages reported up from the widlparser code — as expected — but in spite of those syntax errors, server.py still returns a 200 instead of the expected 400.

---
I don’t understand the widlparser code well, but as far as I can see, it isn’t causing any exception to be raised when it finds a syntax error. And since the server.py code only returns a 400 if it has caught an exception, it just reports a 200 even if the widlparser found a syntax error.

I would try to submit a patch that does something other than trying to catch an exception — but looking at the widlparser source, I don’t understand what mechanism it actually exposes for consuming code to otherwise programatically check if there have been any syntax errors.

**Comment by tabatkins** [comment]
Hm, I assumed the previous "nothing gets printed at all" failures were a result of an error propagating up. I'll look into how to hook it properly for errors, then.

**Comment by sideshowbarker** [comment]
Raised https://github.com/tabatkins/highlighter/issues/14 with a proposed fix
