### ISSUE TITLE
bs-highlighter and bikeshed require different/incompatible versions of pygments

### ISSUE THREAD

**Issue by hober** [tabatkins/highlighter#19]
which makes it a pain to successfully install both bikeshed and bs-highlighter.

**Comment by tabatkins** [comment]
Ah, good catch, I'll kick this one's version up.

**Comment by hober** [comment]
`pip3 install bs-highlighter` still gets a version that requires an incompatible-with-bikeshed version of Pygments, though, @tabatkins.

**Comment by tabatkins** [comment]
Oh duh, thanks for the reminder. Version 2.0.1 published to pip now, sorry about that.

**Comment by hober** [comment]
> Oh duh, thanks for the reminder. Version 2.0.1 published to pip now, sorry about that.

Thank you! :) :)

**Comment by hober** [comment]
Ugh, still doesn't work for me. Sorry, @tabatkins! Here's the error I now see when I `pip3 install bs-highlighter`:

```
Installing collected packages: pygments, bs-highlighter
  Attempting uninstall: pygments
    Found existing installation: Pygments 2.8.1
    Uninstalling Pygments-2.8.1:
      Successfully uninstalled Pygments-2.8.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bikeshed 2.4.0 requires pygments==2.8.1, but you have pygments 2.7.4 which is incompatible.
```

**Comment by tabatkins** [comment]
Ugh, indeed. Okay, *both* of the requirements synced with Bikeshed now, and pushed to pip in 2.0.2.

**Comment by hober** [comment]
> Ugh, indeed. Okay, _both_ of the requirements synced with Bikeshed now, and pushed to pip in 2.0.2.

It works now! Thank you so much, and sorry for all the hassle.

**Comment by tabatkins** [comment]
No problem! Thanks for finding the bug.
