### ISSUE TITLE
WebIDL parsing failures for six WebIDL blocks from HTML spec

### ISSUE THREAD

**Issue by sideshowbarker** [tabatkins/highlighter#4]
The highlighter fails with `Exception: IDL SYNTAX ERROR` when processing each of the six JSON arrays for WebIDL content from the HTML spec in the following file:

* [highlighter-failures.json.txt](https://github.com/tabatkins/highlighter/files/2083922/highlighter-failures.json.txt)

Those correspond to the following six WebIDL blocks in the HTML spec:

* https://html.spec.whatwg.org/multipage/workers.html#abstractworker
* https://html.spec.whatwg.org/multipage/interaction.html#elementcontenteditable
* https://html.spec.whatwg.org/multipage/webappapis.html#globaleventhandlers
* https://html.spec.whatwg.org/multipage/links.html#htmlhyperlinkelementutils
* https://html.spec.whatwg.org/multipage/dom.html#htmlorsvgelement
* https://html.spec.whatwg.org/multipage/embedded-content.html#htmlimageelement

I assume all of the failures are likely due to those instances not being valid WebIDL — and so to make them work as expected with the hightlighter, we probably need to fix the source in the HTML spec — but I’ve not actually confirmed yet whether or not they’re valid (so for now I’m filing this issue here).

**Comment by sideshowbarker** [comment]
The cause for the first six failures listed in the issue seems to be presence of the `mixin`. If I remove that from the IDL, it parses. But I’m confused because looking at the widlparser sources, I see widlparser actually supports `mixin`, and even has test cases for it that pass…

**Comment by tabatkins** [comment]
And I just updated the widlparser a few days ago, hm.

**Comment by tabatkins** [comment]
Ah, found the issue: <https://github.com/plinss/widlparser/issues/34>. When support for mixins was added, the committer misread the spec and thought that the `ReadonlyMember` construction was for readonly members only. Understandable mistake, but actually it just means that the *optional* `Readonly` production is put in front of the member production. So these mixins are failing because the attributes aren't readonly. ^_^

I'll submit a PR to widlparser and then merge this up when it's fixed.

**Comment by sideshowbarker** [comment]
> I'll submit a PR to widlparser and then merge this up when it's fixed.

Super, glad you tracked it down

> So these mixins are failing because the attributes aren't readonly.

Seems like it’d be nice if widlparser emitted a better error message in that case… Something like *Missing attribute Readonly*. But I guess that’s not the way it works

**Comment by tabatkins** [comment]
It *can* work that way, but it wasn't set up to do so. But in any case, it shouldn't be requiring readonly anyway. ^_^
