### ISSUE TITLE
HTML serializer incorrectly emits <br></br> instead of just <br>

### ISSUE THREAD

**Issue by sideshowbarker** [tabatkins/highlighter#7]
Given JSON input with a `br` element, and with `--output html`, the serializer emits `<br></br>`:

```
$ echo '["pre",{},"&lt;pre>",["br",{}],"Hello&lt;/pre>"]' \
  | ./highlighter/__init__.py --output html --just html html

<pre><c- ni>&amp;lt;</c->pre&gt;<br></br>Hello<c- ni>&amp;lt;</c->/pre&gt;</pre>
```

It should instead emit only `<br>`. The `</br>` end tag is a document-conformance error:

https://html.spec.whatwg.org/multipage/syntax.html#elements-2:void-elements-2
> Void elements only have a start tag; end tags must not be specified for void elements.

**Comment by tabatkins** [comment]
Whoops, I didn't add any handling of void elements. Fixed, thanks.
